import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Share } from "./Share";
import { Share_2 } from "./Share_2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <p className="flex justify-center py-5 bg-black">Share Button (Demo) - Sampurna</p>
        <div className="grid grid-cols-2 gap-4">
        <Share />
        <Share_2 />
        </div>
      </body>
    </html>
  );
}
